# Generated by Django 5.0.7 on 2024-07-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='category/images')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
