# Generated by Django 5.0.7 on 2024-07-20 20:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('description_ar', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='items/image')),
                ('count', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('price', models.FloatField()),
                ('discount', models.SmallIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='category',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
