# Generated by Django 5.0.7 on 2024-08-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.SmallIntegerField(choices=[(0, 'cash'), (1, 'Card')], default=None),
            preserve_default=False,
        ),
    ]
