# Generated by Django 5.0.7 on 2024-07-21 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(upload_to='category/images', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
