# Generated by Django 5.0.7 on 2024-08-02 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_delivery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'delivery'), (1, 'drive thru')], default='delivery'),
        ),
    ]
