# Generated by Django 5.0.7 on 2024-08-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_address_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='lang',
            new_name='long',
        ),
    ]
