# Generated by Django 5.0.7 on 2024-08-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_lang_address_long'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('count', models.PositiveIntegerField()),
                ('discount', models.PositiveSmallIntegerField(default=0)),
                ('expire_date', models.DateTimeField()),
            ],
        ),
    ]
