# Generated by Django 5.0.7 on 2024-08-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_coupun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupun',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
