# Generated by Django 5.0.7 on 2024-08-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_coupun_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupun',
            new_name='Coupon',
        ),
    ]
