# Generated by Django 5.0.7 on 2024-07-16 14:58

import api.random
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verify_code',
            field=models.CharField(default=api.random.generate_random_verify_code, max_length=5),
        ),
    ]
